export const GET_HANDWRITING_ID_SUCCESS = 'GET_HANDWRITING_ID_SUCCESS';
export const GET_HANDWRITING_ID_FAIL = 'GET_HANDWRITING_ID_FAIL';
export const GET_HANDWRITINGS_SUCCESS = 'GET_HANDWRITINGS_SUCCESS';
export const GET_HANDWRITINGS_FAIL = 'GET_HANDWRITINGS_FAIL';
export const GET_RENDER_PNG_SUCCESS = 'GET_RENDER_PNG_SUCCESS';
export const GET_RENDER_PNG_FAIL = 'GET_RENDER_PNG_FAIL';
export const GET_RENDER_PDF_SUCCESS = 'GET_RENDER_PDF_SUCCESS';
export const GET_RENDER_PDF_FAIL = 'GET_RENDER_PDF_FAIL';
